Draft: Stac 16209 open telemetry 1 1
StackVista/stackstate-docs pull request #1030
Opened 2022-06-22 07:41 UTC by MelcomVE

2022-06-22 12:51 UTC, TizianoPerrucci requested changes

2022-06-22 12:51 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/mappings.md
> +    - This will be the service displayed under your trace perspective for a specific trace.
we should mention it what the user can use it for

2022-06-22 12:51 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/relations.md
> +Component and Span relations show the relationship between StackState components, for example, the image below shows an example of a relation running from the following to the following components:
`from the following to the following...` ? :thinking:

2022-06-22 12:51 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/merging.md
> +- Add extra attributes into pre-existing StackState components.
all component are StackState components... 

maybe call it consistently pre-existing component ?
this is in several places, search for `StackState component` and change them all

2022-06-23 14:19 UTC, MelcomVE commented on configure/opentelemetry/what-is-opentelemetry-instrumentation.md
> +![trace span example c](../../.gitbook/assets/otel_example_trace_span_c.png)
Definitely forgot to update those

2022-06-26 11:12 UTC, MelcomVE commented on configure/opentelemetry/manual-instrumentation/instrumentation-examples.md
> +// You need to close the spans in the opposite order in which you opended them
Added a comment to what will happen

2022-06-26 12:40 UTC, MelcomVE commented on configure/opentelemetry/manual-instrumentation/mappings.md
> +    - This will be the service displayed under your trace perspective for a specific trace.
I'm unable to find any functionality for this key except enhancing the data you can see in a Trace.

2022-06-27 13:30 UTC, TizianoPerrucci requested changes

2022-06-27 13:30 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/instrumentation-examples.md
> +Let's use a Table from the non exist Database as a child, this allows us to add a critical health state on the child if a write event to this table failed.
`write event` -> `write operation`

2022-06-27 13:30 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/merging.md
> +When you merge your custom instrumentation with a StackState component, it might seem that your component disappeared; it did not.
`pre-existing` StackState component ?

2022-06-27 13:30 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/merging.md
> +When you merge your component with a StackState component, the StackState component will contain all the labels, telemetry, and health from your original component.
... with a `pre-existing` StackState component, the merged component ... ?

2022-06-27 13:30 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/merging.md
> +`identifiers` stayed the same but the `labels` merged, This StackState component now contain the values from both.
`merged` component ?

2022-06-27 13:30 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/mappings.md
> +| **trace.perspective.name**      |   `string`   |     **yes**     |     Any string      | AWS RDS: Hello World Database|
the example value does not the example below, should be `RDS Database: Perspective Name`

2022-06-27 13:30 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/mappings.md
> +| **service.name**                |   `string`   |     **yes**     |     Any string      | AWS RDS: Database            |
the example value does not the example below, should be `RDS Database: Service Name`

2022-06-27 13:30 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/mappings.md
> +| **resource.name**               |   `string`   |     **yes**     |     Any string      | Database                     |
the example value does not the example below, should be `Database`
also to keep the same order as the example move this resource.name row after service.identifier

2022-06-27 13:30 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/mappings.md
> +| **http.status_code**            |   `number`   |     **no**      |     HTML status     | 200                          |
`HTML status` -> `HTTP status`

2022-06-27 13:30 UTC, TizianoPerrucci commented on configure/opentelemetry/manual-instrumentation/mappings.md
> +| ***Key***                       |  ***Type***  | ***Required***  | ***Allowed Value*** | ***Example***                |
can we link each key example to its section ?

2022-07-01 15:03 UTC, merged