STAC-13408: Updated stackstate helm chart changes [WIP for 5.1]
StackVista/stackstate-docs pull request #1141
Opened 2022-08-26 08:59 UTC by zvheerden

2022-09-15 14:28 UTC, julianosk requested changes
It looks good, overall! I think there are a few things that could be improved.

2022-09-15 14:28 UTC, julianosk commented on stackpacks/integrations/kubernetes.md
> +  kubeStateMetrics:
Wrong indentation here

2022-09-15 14:28 UTC, julianosk commented on stackpacks/integrations/kubernetes.md
> +To check the status of the Kubernetes integration, check that the StackState Cluster Agent \(`cluster-agent`\) pod and all of the StackState Agent \(`node-agent`\) pods have status ready.
Add the Checks agent here.

2022-09-21 08:10 UTC, gggina commented on setup/agent/kubernetes.md
>  To integrate with other external services, a separate instance of the [StackState Agent](about-stackstate-agent.md) should be deployed on a standalone VM. Other than [cluster checks](#enable-cluster-
links to section that has been removed

2022-09-23 09:09 UTC, LouisParkin approved these changes

2022-10-04 07:24 UTC, merged