STAC-19841 self hosted installation for Kubernetes Troubleshooting
StackVista/stackstate-docs pull request #1411
Opened 2023-07-21 11:18 UTC by rb3ckers

2023-07-26 09:53 UTC, viliakov commented on setup/install-stackstate/requirements.md
>  # Requirements
Overview contains link to "Linux version"

2023-07-26 09:54 UTC, viliakov commented on setup/install-stackstate/requirements.md
>  # Requirements
And the broken link to  [networking](https://github.com/stackstate-docs-development/v/remco-draft-docs/self-hosted-setup/install-stackstate/requirements#networking)

2023-07-27 08:41 UTC, viliakov commented on setup/install-stackstate/kubernetes_openshift/openshift_install.md
>  ---
The actual values to create SCC for Openshift https://www.notion.so/stackstate/Install-Stackstate-Agent-to-Openshift-d664e46d30cd44f2ae749ce7262fec80?pvs=4#50394cf2b89b43ee8c842a64d4c9da30

```
backup:
  stackGraph:
    securityContext:
      enabled: false
stackstate:
  components:
    all:
      securityContext:
        enabled: false
    kafkaTopicCreate:
      securityContext:
        enabled: false
    ui:
      securityContext:
        enabled: false
elasticsearch:
  prometheus-elasticsearch-exporter:
    securityContext:
      enabled: false
  securityContext:
    enabled: false
  sysctlInitContainer:
    enabled: false
hbase:
  hdfs:
    securityContext:
      enabled: false
    volumePermissions:
      enabled: false
  hbase:
    securityContext:
      enabled: false
  console:
    securityContext:
      enabled: false
  tephra:
    securityContext:
      enabled: false
kafkaup-operator:
  securityContext:
    enabled: false
minio:
  securityContext:
    enabled: false
zookeeper:
  securityContext:
    enabled: false
scc:
  enabled: true
```

2023-07-27 08:43 UTC, viliakov commented on setup/install-stackstate/kubernetes_openshift/openshift_install.md
> +
`Automatically install the Cluster Agent for OpenShift` has to be deleted

2023-07-27 08:46 UTC, viliakov commented on setup/install-stackstate/kubernetes_openshift/openshift_install.md
the SCC for the platform https://gitlab.com/stackvista/devops/helm-charts/-/blob/master/stable/stackstate-k8s/templates/scc.yaml?ref_type=heads

```
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ template "common.fullname.short" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    stackstate.io/note: "Ignored by helm uninstall, has to be deleted manually"
fsGroup:
  type: RunAsAny
groups:
- system:serviceaccounts:{{ .Release.Namespace }}
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- ephemeral
- persistentVolumeClaim
- projected
- secret
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
```

2023-07-27 08:58 UTC, viliakov commented on setup/install-stackstate/kubernetes_openshift/uninstall.md
> +## Remove remaining resources
For the Openshift, the SCC, if enabled, is installed as a Helm pre-hook and prehooks aren't deleted by `helm uninstall`, which means it has to be deleted manually.
I think If the Helm release name is `stackstate` the name of the scc is `stackstate-k8s-stackstate`

 https://gitlab.com/stackvista/devops/helm-charts/-/blob/master/stable/stackstate-k8s/templates/scc.yamlref_type=heads

2023-07-27 10:15 UTC, viliakov commented on setup/install-stackstate/kubernetes_openshift/no_internet/agent_install.md
> +--set-string 'logsAgent.enabled'='true' \
The installation to Openshift has to be done without 
```
--set-string 'logsAgent.enabled'='true'
```
and with
```
--set 'nodeAgent.skipKubeletTLSVerify'=true \
--set 'nodeAgent.scc.enabled'=true \
--set 'openShiftLogging.installSecret'=true \
```

2023-07-27 10:18 UTC, rb3ckers commented on setup/install-stackstate/kubernetes_openshift/no_internet/agent_install.md
> +--set-string 'logsAgent.enabled'='true' \
I know. But AKS is different again etc.. This is all documented in the stackpacks and I don't want to repeat it all here (because it would quadruple this page in size and would require us to update this in 2 places which we'll forget). So I hoped to make that clear with the remark that this is only an example and you should use the command for your k8s distribution from StackState. 

Note that this command can anyway not be copy/pasted unless your the ACME cooperation ;)

2023-07-27 10:23 UTC, viliakov commented on setup/data-management/backup_restore/kubernetes_backup.md
>  {% endhint %}
Two deprecated services are mentioned in the end of this page. Must be deleted
```
kubectl scale --replicas=1 deployment/mm2es
kubectl scale --replicas=1 deployment/trace2es
```

2023-07-27 10:23 UTC, viliakov commented on setup/data-management/backup_restore/kubernetes_backup.md
>  {% endhint %}
And in the middle of the page
```
kubectl scale --replicas=0 deployment/mm2es
kubectl scale --replicas=0 deployment/trace2es
```

2023-07-27 10:33 UTC, viliakov commented on setup/security/authentication/service_tokens.md
>  # Service tokens
I see the some mentions of the old cli have been deleted, but some are still on the page. Did you miss them or leave intentionally?

2023-07-27 11:19 UTC, rb3ckers commented on setup/security/authentication/service_tokens.md
>  # Service tokens
I missed them I guess.

2023-07-28 11:28 UTC, rb3ckers commented on setup/install-stackstate/kubernetes_openshift/openshift_install.md
Nice find that it was just an empty section...

2023-07-28 11:29 UTC, rb3ckers commented on setup/install-stackstate/kubernetes_openshift/openshift_install.md
>  ---
Just checking: For Kafka it doesn't need to be disabled?

2023-07-28 11:52 UTC, viliakov commented on setup/install-stackstate/kubernetes_openshift/openshift_install.md
>  ---
Actually we probably can remove other securityContext-s as well. I can check it against tbe dev Openshift.

2023-07-28 12:27 UTC, viliakov commented on setup/install-stackstate/kubernetes_openshift/openshift_install.md
>  ---
What is really needed is these ones:

```
elasticsearch:
  sysctlInitContainer:
    enabled: false
scc:
  enabled: true
 ```

scc takes care about almost all restrictions

2023-07-30 22:24 UTC, LukaszMarchewka requested changes

2023-07-31 07:15 UTC, LukaszMarchewka requested changes

2023-07-31 07:34 UTC, rb3ckers commented on setup/install-stackstate/initial_run_guide.md
>  * **password:** Set during installation. This is collected by the `generate_values.sh` script and stored in MD5 hash format in `values.yaml`
So did I. We support `bcrypt` but the `generate_values` script doesn't use it. I assume because on a standard linux or system or Mac the tools to generate a bcrypt hash are not installed by default but `md5` or `md5sum` is. 

We'll be changing the helm chart soon to fix this luckily.

2023-08-01 05:47 UTC, LukaszMarchewka commented
https://stackstate.gitbook.io/stackstate-docs-development/v/remco-draft-docs/self-hosted-setup/data-management/backup_restore/kubernetes_backup#disable-restores - can you explain consequences when it is enabled/disabled, means when restore will be executed. For me automatic restore is a warning signal.

2023-08-01 07:13 UTC, rb3ckers commented on setup/data-management/backup_restore/kubernetes_backup.md
> +description: StackState for Kubernetes troubleshooting Self-hosted
I do got know what this exactly means (these docs already existed, I just updated them). We don't do automatic restores (that would be insane) so my best guess is this is whether restores are possible at all.

2023-08-01 07:16 UTC, rb3ckers commented on setup/data-management/backup_restore/kubernetes_backup.md
> +description: StackState for Kubernetes troubleshooting Self-hosted
Wow, that is super confusing and I definitely don't understand why this is using the python timedelta format either. I'd need to reverse engineer how this works form the code/configuration options...

2023-08-01 07:18 UTC, rb3ckers commented on setup/data-management/backup_restore/kubernetes_backup.md
> +description: StackState for Kubernetes troubleshooting Self-hosted
I expect that the string value needs to be a json array, but again. I don't know and will need to reverse engineer this.

2023-08-01 09:01 UTC, LukaszMarchewka commented on setup/data-management/backup_restore/kubernetes_backup.md
> +description: StackState for Kubernetes troubleshooting Self-hosted
but restore is executed by a bash script, and I'm almost sure these scripts communicates with a database directly (e.g. elasticsearch), so I think it is about something else

2023-08-01 11:06 UTC, rb3ckers commented on setup/data-management/backup_restore/kubernetes_backup.md
> +description: StackState for Kubernetes troubleshooting Self-hosted
What I mean is that with this flag you can completely block the restore API of Elasticsearch. Restoring a backup would be impossible with the script. But to be investigated if that's correct.

2023-08-01 11:06 UTC, merged