STAC-20535 Document notifications
StackVista/stackstate-docs pull request #1444
Opened 2023-12-22 15:22 UTC by rb3ckers

2024-01-02 13:50 UTC, rb3ckers commented on use/alerting/notifications/README.md
> +# Notifications
Should we now also update the header in the sidebar from `Monitors & Alerts` to `Monitors & Notifications`?

2024-01-03 07:39 UTC, craffit requested changes

2024-01-03 07:39 UTC, craffit commented on use/alerting/notifications/README.md
> +Notifications in StackState are the way to send alerts to third-party applications, for example incident management tools (like PagerDuty or Opsgenie), ticketing systems (like JIRA, ServiceNow), or o
Notifications are the way to send alerts.. 

Instead of explaining notifications with the 'alert' synonym we might give an actual description and acknowledge the synonym:

Something like
Notifications in StackState are the way to notify third-party applications when a [monitor](../linkylink) in StackState fires. Third-party applications notifications integrate with are for example incident management tools (like PagerDuty or Opsgenie), ticketing systems (like JIRA, ServiceNow), or other collaboration platforms (like Slack). Other tools might refer to notifications as alerts.

2024-01-03 07:39 UTC, craffit commented on use/alerting/notifications/configure.md
> +* [Create a new notification](#create-a-new-notification)
notification => notification configuration

2024-01-03 07:39 UTC, craffit commented on use/alerting/notifications/configure.md
> +Each channel has an interpretation of these messages most fitting for the channel.
I would leave this out sentence, its great that we explain the overall data model here (a notification can be open or closed), users will figure out themselves that channels represent this differently

2024-01-03 07:39 UTC, craffit commented on use/alerting/notifications/channels/webhook.md
> +4. Enable SSL verification - (default on) enable SSL certificate validation. Only disable when using self-signed certificates or certificate authorities not supported by StackState
silly question: did we test this?

2024-01-03 07:39 UTC, craffit commented on use/alerting/notifications/channels/webhook.md
> +5. notification id: A unique identifier for this notification. See also the [Notification life cycle](#notification-life-cycle)
probably needs a capital at the start

2024-01-03 07:39 UTC, craffit commented on use/alerting/notifications/channels/webhook.md
> +## Notification life cycle
very nice, great giving the high-level design rather than just plain 'message types' and have the user figure out intent

2024-01-03 07:39 UTC, craffit commented on use/alerting/notifications/channels/webhook.md
> +1. Save this Python script as `webhook.py`:
nice, this will help users get started

2024-01-03 07:39 UTC, craffit commented on use/alerting/notifications/troubleshooting.md
> +1. Click on the notification
notification configuration?

2024-01-03 08:34 UTC, rb3ckers commented on use/alerting/notifications/troubleshooting.md
> +1. Click on the notification
That's tricky. In the UI these are called `Notification` everywhere

2024-01-03 08:35 UTC, rb3ckers commented on use/alerting/notifications/channels/webhook.md
> +4. Enable SSL verification - (default on) enable SSL certificate validation. Only disable when using self-signed certificates or certificate authorities not supported by StackState
Good question, I'll need to check with Frank

2024-01-03 08:37 UTC, rb3ckers commented on use/alerting/notifications/configure.md
> +* [Create a new notification](#create-a-new-notification)
Yeah, well. The button in the UI says "Notification" as does the entire UI.... That's a discrepancy that usually is not very confusing but in some places it might be.

2024-01-03 08:40 UTC, rb3ckers commented on use/alerting/notifications/README.md
> +Notifications in StackState are the way to send alerts to third-party applications, for example incident management tools (like PagerDuty or Opsgenie), ticketing systems (like JIRA, ServiceNow), or o
Thanks. Was struggling with that explanation. This is much better.

2024-01-03 13:23 UTC, rb3ckers commented on use/alerting/notifications/troubleshooting.md
> +1. Click on the notification
I'll leave it as-is for now (see also discussion in Slack). If it turns out to be too confusing in the future we need not only update the docs but also the UI.

2024-01-03 14:11 UTC, merged