STAC-11738 How to configure self-signed certificates
StackVista/stackstate-docs pull request #259
Opened 2021-01-26 14:57 UTC by rb3ckers

2021-01-26 15:17 UTC, vpartington requested changes

2021-01-26 15:17 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +StackState has several points of interaction with external systems, for example event handlers can call out to webhooks in other systems while plugins can retrieve data from external systems like Spl
"witht" -> "with"

2021-01-26 15:17 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +StackState has several points of interaction with external systems, for example event handlers can call out to webhooks in other systems while plugins can retrieve data from external systems like Spl
"StackState will not be able to communicate" -> "With the default configuration, StackState will not be able to communicate"

2021-01-26 15:17 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +You need an installed JVM (the operating system you're on doesn't matter) to be able to create a new trust store. You also need to have the certificate available, if you don't have that [here](#retri
no "here" link: "[here](#retrieve-certificate-via-the-browser) is a way how to get it" -> "[retrieve them via the browser](#retrieve-certificate-via-the-browser)"

2021-01-26 15:17 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +1. Copy the `cacerts` file from `$JAVA_HOME/lib/security/cacerts` to `custom_cacerts` with `$JAVA_HOME` the location of your Java installation. This environment variable is normally set by the Java i
Give an example command line?

2021-01-26 15:17 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +You need an installed JVM (the operating system you're on doesn't matter) to be able to create a new trust store. You also need to have the certificate available, if you don't have that [here](#retri
"You need an installed JVM (the operating system you're on doesn't matter)" confused me. How about

"To convert an existing TLS certificate file to the format that is needed by StackState, you'll need to use `keytool` tool that is included in the Java Virtual Machine installation. You can run this on any machine, regardless of the type of operating system"

BTW, what about K8s users that don't know about Java? Shouldn't we offer a Docker-based way to do this?

2021-01-26 15:17 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +   The alias needs to be a unique alias for the certificate, for example the domain name itself without any dots. Keytool will ask for a password, the JVM default password is `changeit`.
What does it mean that `changeit` is the default? Is that what will be chosen if I press Enter?

2021-01-26 15:17 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +For Kubernetes installations the trust store and the password can be specified as values. Since the store is a file it can only be specified from the helm command line. We specify the password value
Shouldn't we tell users to use the `values.yaml` approach here? `--set-file` and `--set` are messy.

In fact, shouldn't we update the `generate_values.sh` script (I still prefer that over the CLI) to generate this?

2021-01-26 15:50 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +1. Copy the `cacerts` file from `$JAVA_HOME/lib/security/cacerts` to `custom_cacerts` with `$JAVA_HOME` the location of your Java installation. This environment variable is normally set by the Java i
For Linux, WIndows, Mac or all 3?

2021-01-26 15:53 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +For Kubernetes installations the trust store and the password can be specified as values. Since the store is a file it can only be specified from the helm command line. We specify the password value
I wouldn't want to polute our values yaml with something only a few customers ever use. I don't know of a way how to put a binary file in a `values.yaml` that is not super messy (i.e. take file, base64 encode and put 50kb of garbage into a text file). So for binary files I always prefer `--set-file` and to not compliate matters more here I give the example completely like this. I'm fine with putting the password into a values file if you prefer that.

2021-01-26 15:54 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +1. Copy the `cacerts` file from `$JAVA_HOME/lib/security/cacerts` to `custom_cacerts` with `$JAVA_HOME` the location of your Java installation. This environment variable is normally set by the Java i
Serious question though. I don't know what we do in general in the docs.

2021-01-26 15:55 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +You need an installed JVM (the operating system you're on doesn't matter) to be able to create a new trust store. You also need to have the certificate available, if you don't have that [here](#retri
Not sure how far you want to go with that. My experience is that our customers are more likely to have a JVM than to have a docker daemon installed. But I can add that as an alternative.

2021-01-26 16:10 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +   The alias needs to be a unique alias for the certificate, for example the domain name itself without any dots. Keytool will ask for a password, the JVM default password is `changeit`.
YOu should use the password `changeit`. Rephrased.

2021-01-27 05:59 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +You need an installed JVM (the operating system you're on doesn't matter) to be able to create a new trust store. You also need to have the certificate available, if you don't have that [here](#retri
I can imagine our current customers are more likely to have a JVM installed. But would that not also be caused by the fact that you need a JVM to run the Linux install for StackState?

But you're right, let's stick to what we need to now and not add even more work to our backlog.

2021-01-27 06:00 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +1. Copy the `cacerts` file from `$JAVA_HOME/lib/security/cacerts` to `custom_cacerts` with `$JAVA_HOME` the location of your Java installation. This environment variable is normally set by the Java i
Ah yes. macOS and Linux commands tend to be the same, but I forgot about Windows.

Maybe just give an example for Linux/macOS then?

2021-01-27 06:05 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +   The alias needs to be a unique alias for the certificate, for example the domain name itself without any dots. Keytool will ask for a password, the JVM default password is `changeit`.
BTW, is that the password for the keystore (that can be set with `-storepasswd`) or the one for the key itself (`-keypasswd`)? Maybe you add (one of) those two arguments to the command so that the prompt isn't shown and so that it is clear what value to put here and what value to set in the `values.yaml` file?

2021-01-27 06:09 UTC, vpartington commented on configure/security/self-signed-certificates.md
> +For Kubernetes installations the trust store and the password can be specified as values. Since the store is a file it can only be specified from the helm command line. We specify the password value
I see why you'd prefer the `--set-file` option. However, I can imagine users forgetting to add the `--set-file` option when upgrading. The upgrade will appear to succeed, but some of the integrations will start failing later on. Maybe even the alerting is this was used to communicate with an external notification service that was set up with self-signed certs. Unfortunately StS is not very good at checking its own status yet, so it might be a while before they find out. I can imagine some irate tickets coming in when they do find out.

Base64-encoding is ugly indeed, but the `generate_values.sh` script would be able to do that for the user.

2021-01-27 07:43 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +1. Copy the `cacerts` file from `$JAVA_HOME/lib/security/cacerts` to `custom_cacerts` with `$JAVA_HOME` the location of your Java installation. This environment variable is normally set by the Java i
I now added the linux / mac version (which I think should be the same)

2021-01-27 07:44 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +You need an installed JVM (the operating system you're on doesn't matter) to be able to create a new trust store. You also need to have the certificate available, if you don't have that [here](#retri
Added a docker example as well. I personally prefer that way actually

2021-01-27 09:39 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +   The alias needs to be a unique alias for the certificate, for example the domain name itself without any dots. Keytool will ask for a password, the JVM default password is `changeit`.
I didn't even know about the `keypasswd`. This is the default password on the store itself. `keytool` always asks this automatically.

2021-01-27 09:40 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +For Kubernetes installations the trust store and the password can be specified as values. Since the store is a file it can only be specified from the helm command line. We specify the password value
Let's discuss this offline like you suggested.

2021-01-27 14:56 UTC, rb3ckers commented on configure/security/self-signed-certificates.md
> +For Kubernetes installations the trust store and the password can be specified as values. Since the store is a file it can only be specified from the helm command line. We specify the password value
Discussed and we've decided to stick with the `set-files`

2021-03-01 09:35 UTC, merged