STAC-11770 Add documentation on Elasticsearch privileged containers
StackVista/stackstate-docs pull request #261
Opened 2021-01-27 09:37 UTC by rb3ckers

2021-01-27 09:44 UTC, rb3ckers commented on setup/installation/kubernetes_install/required_permissions.md
> +```yaml
I think it is a good idea to have this as an example here. If you agree I'll run a test for this as well (not yet verified this works properly, but it should)

2021-01-29 07:28 UTC, vpartington requested changes
Dependening on the answer to my question, you might want to add a paragraph that explains what happens if the administrators disables the sysctlInitContainer but does not perform the other actions.

2021-01-29 07:28 UTC, vpartington commented on setup/installation/kubernetes_install/required_permissions.md
> +```yaml
Wow, that is pretty elaborate. 

And probably a good idea because if we don't provide this, we'll either get asked how to do this or people don't do it which will lead to ElasticSearch issues later on.

Or does ElasticSearch check that the values have been set correctly at startup? If that is the case, you might want to mention that explicitly, including the error message so that administrators will be able to quickly find this section if they forget to set it or the config breaks in some other way.

2021-01-29 08:00 UTC, rb3ckers commented on setup/installation/kubernetes_install/required_permissions.md
> +```yaml
I thought I mentioned that already, but if not will add it and add the error message ES gives. Because it does check on starup and will just fail to startup with a very clear error message saying something along the lines `vm.max_map_count is abc but should be greater than or equal to xyz`.

2021-01-29 09:42 UTC, rb3ckers commented on setup/installation/kubernetes_install/required_permissions.md
> +```yaml
Added example error

2021-01-29 10:41 UTC, rb3ckers commented on setup/installation/kubernetes_install/required_permissions.md
> +All of StackState's own components can run without any extra permissions. However StackState uses Elasticsearch which has some extra requirements on the nodes it runs on. To make sure those requireme
The sentence from "To make sure" is a bit weird and hard to understand I just noticed

2021-02-04 12:28 UTC, merged