Stac 15432 add storage reqs for cops
StackVista/stackstate-docs pull request #942
Opened 2022-03-18 09:34 UTC by rfosterstackstate

2022-03-18 10:52 UTC, vpartington requested changes

2022-03-18 10:52 UTC, vpartington commented on setup/install-stackstate/requirements.md
> +For KOTS deployments you need to make sure there is at least 80GB allocate to the root (`/`) partition. Further to this it is advised you should allocate at least 500GB to `/var`.
The 512 Gi should go to `/var/lib/longhorn`. The rest of `/var` can be on the root partition and will use up that 80 Gi.

2022-03-18 10:52 UTC, vpartington commented on setup/install-stackstate/requirements.md
> +For KOTS deployments you need to make sure there is at least 80GB allocate to the root (`/`) partition. Further to this it is advised you should allocate at least 500GB to `/var`.
Also, I would make it a bullet list. They're easier to scan then proza.

2022-03-23 09:18 UTC, gggina commented on setup/install-stackstate/requirements.md
> +
For KOTS deployments, disks should be partitioned as follows:

* `/` - at least 80GB
* `/var/lib/longhorn` - at least 500GB with a latency of < 10ms

The following example cloud VM instance/disk combinations are known to provide sufficient performance for etcd and will pass the write latency preflight check.

* AWS m4.xlarge with 80 GB standard EBS root device
* Azure D4ds_v4 with 80 GB ultra disk mounted at `/var/lib/etcd` provisioned with 2400 IOPS and 128 MB/s throughput
* Google Cloud Platform n1-standard-4 with 500 GB pd-standard boot disk

2022-03-24 09:43 UTC, merged